# Generated by Django 4.1.7 on 2023-03-10 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact_us",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("mobile", models.CharField(max_length=14)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=500)),
                ("capacity", models.IntegerField()),
                ("desc", models.TextField()),
                ("image", models.ImageField(upload_to="venue")),
            ],
        ),
        migrations.CreateModel(
            name="Book_event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=14)),
                ("email", models.EmailField(max_length=254)),
                ("location", models.CharField(max_length=100)),
                ("people", models.IntegerField()),
                ("date", models.DateField()),
                ("event", models.CharField(max_length=100)),
                ("food", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=500)),
                ("message", models.TextField()),
                (
                    "venue",
                    models.ForeignKey(
                        default=" ",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.venue",
                    ),
                ),
            ],
        ),
    ]
