# Generated by Django 4.1.7 on 2023-03-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_contact_us_venue_book_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("package", models.CharField(max_length=200)),
                ("item1", models.CharField(max_length=50)),
                ("item2", models.CharField(max_length=50)),
                ("item3", models.CharField(max_length=50)),
                ("item4", models.CharField(max_length=50)),
                ("pack_price", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="book_event",
            name="location",
        ),
    ]
