# Generated by Django 4.1.7 on 2023-03-12 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_food_remove_book_event_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="culture",
            name="food",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="website.food",
            ),
        ),
    ]
