# Generated by Django 4.1.7 on 2023-03-12 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_alter_culture_food"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="food",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="website.food",
            ),
        ),
        migrations.AlterField(
            model_name="charity",
            name="food",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="website.food",
            ),
        ),
        migrations.AlterField(
            model_name="family",
            name="food",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="website.food",
            ),
        ),
    ]
