# Generated by Django 4.1.7 on 2023-03-16 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_alter_business_food_alter_charity_food_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book_event",
            name="food",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="website.food",
            ),
        ),
    ]
