# Generated by Django 4.1.7 on 2023-03-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_book_event_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="price",
            field=models.IntegerField(default=5000),
            preserve_default=False,
        ),
    ]
