# Generated by Django 4.1.7 on 2023-03-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_venue_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="book_event",
            name="bill",
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
